### ISSUE TITLE
PHP8.0 Migration: decode strings, which were encoded in older php e.g 7.4 version 

### ISSUE THREAD

**Issue by moabazid** [mordilion/huffman-php#1]
The sorting functions in PHP 8.0 have been adjusted. this has an effect on the encoding and decoding of texts. So you cannot decode texts that have already been encoded in Php7.4, when you want to update your tool to php8.0.

**Comment by mordilion** [comment]
What behavior do you mean? As I know there is an issue if I would return a boolean instead of an integer in the callback methods of the sorting methods. But I am only using the Spaceship-Operator, which should be safe. 

If I am overseeing something, please describe it and I will see what I can do.

**Comment by mordilion** [comment]
I found the Issue and build a fix for it. Because it's a breaking change I created directly a v2.0.0 release.
